# Generated by Django 5.1.6 on 2025-02-19 08:01

import account.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='images/avatar_user', validators=[account.validators.validate_avatar_size], verbose_name='عکس پروفایل'),
        ),
    ]
