# Generated by Django 5.1.6 on 2025-04-09 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_commentproduct_reply'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productfavorite',
            options={'verbose_name': 'محصول مورد علاقه', 'verbose_name_plural': ' محصولات مورد علاقه کاربران'},
        ),
    ]
