# Generated by Django 5.1.6 on 2025-02-19 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('image', models.ImageField(upload_to='images/about_us', verbose_name='عکس')),
                ('content', models.TextField(verbose_name='متن درباره ما')),
            ],
            options={
                'verbose_name': 'متن درباره ما',
                'verbose_name_plural': 'متن درباره ما',
            },
        ),
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('full_name', models.CharField(max_length=300, verbose_name='نام و نام خانوادگی')),
                ('email', models.EmailField(max_length=300, verbose_name='ایمیل')),
                ('phone_number', models.CharField(max_length=11, verbose_name='شماره همراه')),
                ('subject', models.CharField(max_length=300, verbose_name='موضوع پیام')),
                ('content', models.TextField(max_length=2048, verbose_name='متن پیام')),
            ],
            options={
                'verbose_name': 'ارتباط با ما',
                'verbose_name_plural': 'پیام های مشتریان',
            },
        ),
    ]
