# Generated by Django 5.1.6 on 2025-03-27 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_footerbox_informationshop_licence_service_sliderhome_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=500, verbose_name='نام و نام خانوادگی')),
                ('image', models.ImageField(upload_to='images/employees', verbose_name='عکس')),
                ('position', models.CharField(max_length=300, verbose_name='سمت')),
            ],
            options={
                'verbose_name': 'مشخصات کارمند',
                'verbose_name_plural': 'مشخصات کارمندان',
            },
        ),
    ]
