# Generated by Django 5.1.6 on 2025-04-07 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_employees'),
    ]

    operations = [
        migrations.AddField(
            model_name='informationshop',
            name='phone',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='تلفن ثابت'),
        ),
    ]
